GRANT SELECT ON public.experiencias TO anon, authenticated;
GRANT SELECT ON public.pesos TO anon, authenticated;
GRANT SELECT ON public.senales TO anon, authenticated;
GRANT SELECT ON public.vetos TO anon, authenticated;
GRANT SELECT, INSERT ON public.recomendaciones TO anon, authenticated;
GRANT SELECT, INSERT ON public.descartes TO anon, authenticated;
GRANT ALL ON public.experiencias TO service_role;
GRANT ALL ON public.pesos TO service_role;
GRANT ALL ON public.senales TO service_role;
GRANT ALL ON public.vetos TO service_role;
GRANT ALL ON public.recomendaciones TO service_role;
GRANT ALL ON public.descartes TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;